### PR TITLE
Added new feature (i.e., classification)

### PR DESCRIPTION
**Pull request by anik123**
Changes:

1. Added a classification algorithm (i.e., Decision Tree (DT)). 
2. Added support for non numeric data. 
3. Added a simple accuracy check in DT.

### CODE REVIEW

**Comment by kate-holdener** [comment]
@anik123 Thank you for the pull request. I tested the code and the classification part that you added works.
One problem is that the linear regression got broken (my guess is that this is due to the change you added to the split_data template). Here are the steps to replicate:
1. Use the data/possum.csv as the input data file
2. Select Clean data
3. In the Prepare Model select "eye" and "continuous" (although, continuous is not being used right now)
4. Exclude "Pop" and "sex" from the x_values
5. Select Split and use default 80/20 split
6. Use the linear regression to train model

At the last step, I get an error on the server side:
Traceback (most recent call last):
  File "/Users/holdenerea/repos/ml_code_generator/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/holdenerea/repos/ml_code_generator/venv/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/holdenerea/repos/ml_code_generator/venv/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/holdenerea/repos/ml_code_generator/venv/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/holdenerea/repos/ml_code_generator/flask_app/api/views.py", line 86, in train_model
    generator.train_model()
  File "/Users/holdenerea/repos/ml_code_generator/application/code_generator.py", line 51, in train_model
    model = self._parse_and_execute('train_model', ['x_train', 'y_train'])
  File "/Users/holdenerea/repos/ml_code_generator/application/code_generator.py", line 81, in _parse_and_execute
    output = self.function_mapping[template](replaced_args)  # where the code is executed
  File "/Users/holdenerea/repos/ml_code_generator/pandas_code/code_templates/train_model.py", line 5, in get_code
    model = LinearRegression().fit(args[0], args[1])
  File "/Users/holdenerea/repos/ml_code_generator/venv/lib/python3.9/site-packages/sklearn/linear_model/_base.py", line 684, in fit
    X, y = self._validate_data(
  File "/Users/holdenerea/repos/ml_code_generator/venv/lib/python3.9/site-packages/sklearn/base.py", line 596, in _validate_data
    X, y = check_X_y(X, y, **check_params)
  File "/Users/holdenerea/repos/ml_code_generator/venv/lib/python3.9/site-packages/sklearn/utils/validation.py", line 1074, in check_X_y
    X = check_array(
  File "/Users/holdenerea/repos/ml_code_generator/venv/lib/python3.9/site-packages/sklearn/utils/validation.py", line 871, in check_array
    raise ValueError(
ValueError: Expected 2D array, got scalar array instead:
array=x_train.
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

**Comment by kate-holdener** [comment]
@anik123 I use GitHub actions to run various tests on the code. One of the actions runs pylint, to check for code format consistency. Pylint reported a few errors (happens all the time): https://github.com/kate-holdener/ml_code_generator/actions/runs/3449586848

**Comment by anik123** [comment]
Dear Dr. @kate-holdener ,

Thanks for your feedback. I will give it a look and will update once I adjusted the comments. 


Thanks.

**Comment by anik123** [comment]
> @anik123 Thank you for the pull request. I tested the code and the classification part that you added works. One problem is that the linear regression got broken (my guess is that this is due to the change you added to the split_data template). Here are the steps to replicate:
> 
> 1. Use the data/possum.csv as the input data file
> 2. Select Clean data
> 3. In the Prepare Model select "eye" and "continuous" (although, continuous is not being used right now)
> 4. Exclude "Pop" and "sex" from the x_values
> 5. Select Split and use default 80/20 split
> 6. Use the linear regression to train model
> 
> At the last step, I get an error on the server side: Traceback (most recent call last): File "/Users/holdenerea/repos/ml_code_generator/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app response = self.full_dispatch_request() File "/Users/holdenerea/repos/ml_code_generator/venv/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request rv = self.handle_user_exception(e) File "/Users/holdenerea/repos/ml_code_generator/venv/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request rv = self.dispatch_request() File "/Users/holdenerea/repos/ml_code_generator/venv/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args) File "/Users/holdenerea/repos/ml_code_generator/flask_app/api/views.py", line 86, in train_model generator.train_model() File "/Users/holdenerea/repos/ml_code_generator/application/code_generator.py", line 51, in train_model model = self._parse_and_execute('train_model', ['x_train', 'y_train']) File "/Users/holdenerea/repos/ml_code_generator/application/code_generator.py", line 81, in _parse_and_execute output = self.function_mapping[template](replaced_args) # where the code is executed File "/Users/holdenerea/repos/ml_code_generator/pandas_code/code_templates/train_model.py", line 5, in get_code model = LinearRegression().fit(args[0], args[1]) File "/Users/holdenerea/repos/ml_code_generator/venv/lib/python3.9/site-packages/sklearn/linear_model/_base.py", line 684, in fit X, y = self._validate_data( File "/Users/holdenerea/repos/ml_code_generator/venv/lib/python3.9/site-packages/sklearn/base.py", line 596, in _validate_data X, y = check_X_y(X, y, **check_params) File "/Users/holdenerea/repos/ml_code_generator/venv/lib/python3.9/site-packages/sklearn/utils/validation.py", line 1074, in check_X_y X = check_array( File "/Users/holdenerea/repos/ml_code_generator/venv/lib/python3.9/site-packages/sklearn/utils/validation.py", line 871, in check_array raise ValueError( ValueError: Expected 2D array, got scalar array instead: array=x_train. Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

Dear Dr. @kate-holdener , 


I could reproduce the error.I have added a video regarding this. Please check and share your feedback. 


https://drive.google.com/file/d/1INDJr8tvZ0_2-gcSHpOpdf7Qxk5P-ubh/view?usp=share_link


Thanks.

**Comment by anik123** [comment]
> @anik123 Thank you for the pull request. I tested the code and the classification part that you added works. One problem is that the linear regression got broken (my guess is that this is due to the change you added to the split_data template). Here are the steps to replicate:
> 
> 1. Use the data/possum.csv as the input data file
> 2. Select Clean data
> 3. In the Prepare Model select "eye" and "continuous" (although, continuous is not being used right now)
> 4. Exclude "Pop" and "sex" from the x_values
> 5. Select Split and use default 80/20 split
> 6. Use the linear regression to train model
> 
> At the last step, I get an error on the server side: Traceback (most recent call last): File "/Users/holdenerea/repos/ml_code_generator/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app response = self.full_dispatch_request() File "/Users/holdenerea/repos/ml_code_generator/venv/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request rv = self.handle_user_exception(e) File "/Users/holdenerea/repos/ml_code_generator/venv/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request rv = self.dispatch_request() File "/Users/holdenerea/repos/ml_code_generator/venv/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args) File "/Users/holdenerea/repos/ml_code_generator/flask_app/api/views.py", line 86, in train_model generator.train_model() File "/Users/holdenerea/repos/ml_code_generator/application/code_generator.py", line 51, in train_model model = self._parse_and_execute('train_model', ['x_train', 'y_train']) File "/Users/holdenerea/repos/ml_code_generator/application/code_generator.py", line 81, in _parse_and_execute output = self.function_mapping[template](replaced_args) # where the code is executed File "/Users/holdenerea/repos/ml_code_generator/pandas_code/code_templates/train_model.py", line 5, in get_code model = LinearRegression().fit(args[0], args[1]) File "/Users/holdenerea/repos/ml_code_generator/venv/lib/python3.9/site-packages/sklearn/linear_model/_base.py", line 684, in fit X, y = self._validate_data( File "/Users/holdenerea/repos/ml_code_generator/venv/lib/python3.9/site-packages/sklearn/base.py", line 596, in _validate_data X, y = check_X_y(X, y, **check_params) File "/Users/holdenerea/repos/ml_code_generator/venv/lib/python3.9/site-packages/sklearn/utils/validation.py", line 1074, in check_X_y X = check_array( File "/Users/holdenerea/repos/ml_code_generator/venv/lib/python3.9/site-packages/sklearn/utils/validation.py", line 871, in check_array raise ValueError( ValueError: Expected 2D array, got scalar array instead: array=x_train. Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

Dear Dr. @kate-holdener , 


I couldn't reproduce the error. I have created a video regarding this. Please check the following link and share your feedback. 

https://drive.google.com/file/d/1INDJr8tvZ0_2-gcSHpOpdf7Qxk5P-ubh/view?usp=share_link


Thanks.

**Comment by kate-holdener** [comment]
> > @anik123 Thank you for the pull request. I tested the code and the classification part that you added works. One problem is that the linear regression got broken (my guess is that this is due to the change you added to the split_data template). Here are the steps to replicate:
> > 
> > 1. Use the data/possum.csv as the input data file
> > 2. Select Clean data
> > 3. In the Prepare Model select "eye" and "continuous" (although, continuous is not being used right now)
> > 4. Exclude "Pop" and "sex" from the x_values
> > 5. Select Split and use default 80/20 split
> > 6. Use the linear regression to train model
> > 
> > At the last step, I get an error on the server side: Traceback (most recent call last): File "/Users/holdenerea/repos/ml_code_generator/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app response = self.full_dispatch_request() File "/Users/holdenerea/repos/ml_code_generator/venv/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request rv = self.handle_user_exception(e) File "/Users/holdenerea/repos/ml_code_generator/venv/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request rv = self.dispatch_request() File "/Users/holdenerea/repos/ml_code_generator/venv/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args) File "/Users/holdenerea/repos/ml_code_generator/flask_app/api/views.py", line 86, in train_model generator.train_model() File "/Users/holdenerea/repos/ml_code_generator/application/code_generator.py", line 51, in train_model model = self._parse_and_execute('train_model', ['x_train', 'y_train']) File "/Users/holdenerea/repos/ml_code_generator/application/code_generator.py", line 81, in _parse_and_execute output = self.function_mapping[template](replaced_args) # where the code is executed File "/Users/holdenerea/repos/ml_code_generator/pandas_code/code_templates/train_model.py", line 5, in get_code model = LinearRegression().fit(args[0], args[1]) File "/Users/holdenerea/repos/ml_code_generator/venv/lib/python3.9/site-packages/sklearn/linear_model/_base.py", line 684, in fit X, y = self._validate_data( File "/Users/holdenerea/repos/ml_code_generator/venv/lib/python3.9/site-packages/sklearn/base.py", line 596, in _validate_data X, y = check_X_y(X, y, **check_params) File "/Users/holdenerea/repos/ml_code_generator/venv/lib/python3.9/site-packages/sklearn/utils/validation.py", line 1074, in check_X_y X = check_array( File "/Users/holdenerea/repos/ml_code_generator/venv/lib/python3.9/site-packages/sklearn/utils/validation.py", line 871, in check_array raise ValueError( ValueError: Expected 2D array, got scalar array instead: array=x_train. Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.
> 
> Dear Dr. @kate-holdener ,
> 
> I couldn't reproduce the error. I have created a video regarding this. Please check the following link and share your feedback.
> 
> https://drive.google.com/file/d/1INDJr8tvZ0_2-gcSHpOpdf7Qxk5P-ubh/view?usp=share_link
> 
> Thanks.

@anik123 I cannot seem to replicate this problem now either. I must have missed a step in my description. I'll keep trying to make it happen. 

In my attempts to make it happen, I caused train_c step to crash. Same steps as above but instead of step 6 using linear regression for training, I clicked on "classification". Note, I was using "Next Actions" to get back to the screen of various options (instead of the browser back button). Here is the error I got:
Traceback (most recent call last):
  File "/Users/holdenerea/repos/ml_code_generator/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/holdenerea/repos/ml_code_generator/venv/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/holdenerea/repos/ml_code_generator/venv/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/holdenerea/repos/ml_code_generator/venv/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/holdenerea/repos/ml_code_generator/flask_app/api/views.py", line 90, in train_model_c
    generator.train_model_c()
  File "/Users/holdenerea/repos/ml_code_generator/application/code_generator.py", line 55, in train_model_c
    model = self._parse_and_execute('train_model_c', ['x_train', 'y_train','x_test', 'y_test'])
  File "/Users/holdenerea/repos/ml_code_generator/application/code_generator.py", line 81, in _parse_and_execute
    output = self.function_mapping[template](replaced_args)  # where the code is executed
  File "/Users/holdenerea/repos/ml_code_generator/pandas_code/code_templates/train_model_c.py", line 6, in get_code
    model = DecisionTreeClassifier().fit(args[0], args[1])
  File "/Users/holdenerea/repos/ml_code_generator/venv/lib/python3.9/site-packages/sklearn/tree/_classes.py", line 969, in fit
    super().fit(
  File "/Users/holdenerea/repos/ml_code_generator/venv/lib/python3.9/site-packages/sklearn/tree/_classes.py", line 210, in fit
    check_classification_targets(y)
  File "/Users/holdenerea/repos/ml_code_generator/venv/lib/python3.9/site-packages/sklearn/utils/multiclass.py", line 200, in check_classification_targets
    raise ValueError("Unknown label type: %r" % y_type)
ValueError: Unknown label type: 'continuous'

Here is a recording I made replicating this new problem: https://drive.google.com/file/d/11gOy8f6MOj6ubeuoiwRyA771fg723Gb5/view?usp=sharing


I'll keep trying to figure out how I caused the original crash.

**Comment by anik123** [comment]
> > > @anik123 Thank you for the pull request. I tested the code and the classification part that you added works. One problem is that the linear regression got broken (my guess is that this is due to the change you added to the split_data template). Here are the steps to replicate:
> > > 
> > > 1. Use the data/possum.csv as the input data file
> > > 2. Select Clean data
> > > 3. In the Prepare Model select "eye" and "continuous" (although, continuous is not being used right now)
> > > 4. Exclude "Pop" and "sex" from the x_values
> > > 5. Select Split and use default 80/20 split
> > > 6. Use the linear regression to train model
> > > 
> > > At the last step, I get an error on the server side: Traceback (most recent call last): File "/Users/holdenerea/repos/ml_code_generator/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app response = self.full_dispatch_request() File "/Users/holdenerea/repos/ml_code_generator/venv/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request rv = self.handle_user_exception(e) File "/Users/holdenerea/repos/ml_code_generator/venv/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request rv = self.dispatch_request() File "/Users/holdenerea/repos/ml_code_generator/venv/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args) File "/Users/holdenerea/repos/ml_code_generator/flask_app/api/views.py", line 86, in train_model generator.train_model() File "/Users/holdenerea/repos/ml_code_generator/application/code_generator.py", line 51, in train_model model = self._parse_and_execute('train_model', ['x_train', 'y_train']) File "/Users/holdenerea/repos/ml_code_generator/application/code_generator.py", line 81, in _parse_and_execute output = self.function_mapping[template](replaced_args) # where the code is executed File "/Users/holdenerea/repos/ml_code_generator/pandas_code/code_templates/train_model.py", line 5, in get_code model = LinearRegression().fit(args[0], args[1]) File "/Users/holdenerea/repos/ml_code_generator/venv/lib/python3.9/site-packages/sklearn/linear_model/_base.py", line 684, in fit X, y = self._validate_data( File "/Users/holdenerea/repos/ml_code_generator/venv/lib/python3.9/site-packages/sklearn/base.py", line 596, in _validate_data X, y = check_X_y(X, y, **check_params) File "/Users/holdenerea/repos/ml_code_generator/venv/lib/python3.9/site-packages/sklearn/utils/validation.py", line 1074, in check_X_y X = check_array( File "/Users/holdenerea/repos/ml_code_generator/venv/lib/python3.9/site-packages/sklearn/utils/validation.py", line 871, in check_array raise ValueError( ValueError: Expected 2D array, got scalar array instead: array=x_train. Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.
> > 
> > 
> > Dear Dr. @kate-holdener ,
> > I couldn't reproduce the error. I have created a video regarding this. Please check the following link and share your feedback.
> > https://drive.google.com/file/d/1INDJr8tvZ0_2-gcSHpOpdf7Qxk5P-ubh/view?usp=share_link
> > Thanks.
> 
> @anik123 I cannot seem to replicate this problem now either. I must have missed a step in my description. I'll keep trying to make it happen.
> 
> In my attempts to make it happen, I caused train_c step to crash. Same steps as above but instead of step 6 using linear regression for training, I clicked on "classification". Note, I was using "Next Actions" to get back to the screen of various options (instead of the browser back button). Here is the error I got: Traceback (most recent call last): File "/Users/holdenerea/repos/ml_code_generator/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app response = self.full_dispatch_request() File "/Users/holdenerea/repos/ml_code_generator/venv/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request rv = self.handle_user_exception(e) File "/Users/holdenerea/repos/ml_code_generator/venv/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request rv = self.dispatch_request() File "/Users/holdenerea/repos/ml_code_generator/venv/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args) File "/Users/holdenerea/repos/ml_code_generator/flask_app/api/views.py", line 90, in train_model_c generator.train_model_c() File "/Users/holdenerea/repos/ml_code_generator/application/code_generator.py", line 55, in train_model_c model = self._parse_and_execute('train_model_c', ['x_train', 'y_train','x_test', 'y_test']) File "/Users/holdenerea/repos/ml_code_generator/application/code_generator.py", line 81, in _parse_and_execute output = self.function_mapping[template](replaced_args) # where the code is executed File "/Users/holdenerea/repos/ml_code_generator/pandas_code/code_templates/train_model_c.py", line 6, in get_code model = DecisionTreeClassifier().fit(args[0], args[1]) File "/Users/holdenerea/repos/ml_code_generator/venv/lib/python3.9/site-packages/sklearn/tree/_classes.py", line 969, in fit super().fit( File "/Users/holdenerea/repos/ml_code_generator/venv/lib/python3.9/site-packages/sklearn/tree/_classes.py", line 210, in fit check_classification_targets(y) File "/Users/holdenerea/repos/ml_code_generator/venv/lib/python3.9/site-packages/sklearn/utils/multiclass.py", line 200, in check_classification_targets raise ValueError("Unknown label type: %r" % y_type) ValueError: Unknown label type: 'continuous'
> 
> Here is a recording I made replicating this new problem: https://drive.google.com/file/d/11gOy8f6MOj6ubeuoiwRyA771fg723Gb5/view?usp=sharing
> 
> I'll keep trying to figure out how I caused the original crash.

ok. Thanks.

**Comment by anik123** [comment]
> @anik123 I use GitHub actions to run various tests on the code. One of the actions runs pylint, to check for code format consistency. Pylint reported a few errors (happens all the time): https://github.com/kate-holdener/ml_code_generator/actions/runs/3449586848

This happens due to long chain code that I wrote in split file. Their testing scheme doesn't recommend to write long single line code. I will simplify it.

**Comment by kate-holdener** [comment]
Closing this pull request without merging.

**Pull request closed without merging**
